/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Tiffany
 */
import java.text.DecimalFormat;
import java.util.Arrays;
import java.util.*;
public class GPAcalc extends javax.swing.JFrame {
    private int numClasses = 0;
    private int[] classes = new int[8];
    private int[] exams = new int[8];
    ArrayList<Integer> nonscale = new ArrayList<>();
    ArrayList<Double> scale = new ArrayList<>();
    ArrayList<Boolean> we = new ArrayList<>();
    /**
     * Creates new form GPAcalc
     */
    public GPAcalc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        sem1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sem2 = new javax.swing.JTextField();
        sem3 = new javax.swing.JTextField();
        sem4 = new javax.swing.JTextField();
        sem5 = new javax.swing.JTextField();
        sem6 = new javax.swing.JTextField();
        sem7 = new javax.swing.JTextField();
        sem8 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ex1 = new javax.swing.JTextField();
        ex2 = new javax.swing.JTextField();
        ex3 = new javax.swing.JTextField();
        ex4 = new javax.swing.JTextField();
        ex5 = new javax.swing.JTextField();
        ex6 = new javax.swing.JTextField();
        ex7 = new javax.swing.JTextField();
        ex8 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        weight1 = new javax.swing.JRadioButton();
        weight2 = new javax.swing.JRadioButton();
        weight3 = new javax.swing.JRadioButton();
        weight4 = new javax.swing.JRadioButton();
        weight5 = new javax.swing.JRadioButton();
        weight6 = new javax.swing.JRadioButton();
        weight7 = new javax.swing.JRadioButton();
        weight8 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        calcGPA = new javax.swing.JButton();
        gpa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("GPA Calculator");

        sem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Final Exam");

        sem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem2ActionPerformed(evt);
            }
        });

        sem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem3ActionPerformed(evt);
            }
        });

        sem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem4ActionPerformed(evt);
            }
        });

        sem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem5ActionPerformed(evt);
            }
        });

        sem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem6ActionPerformed(evt);
            }
        });

        sem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem7ActionPerformed(evt);
            }
        });

        sem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sem8ActionPerformed(evt);
            }
        });

        jLabel3.setText("Semester ");

        ex1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ex1ActionPerformed(evt);
            }
        });

        ex2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ex2ActionPerformed(evt);
            }
        });

        ex3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ex3ActionPerformed(evt);
            }
        });

        ex4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ex4ActionPerformed(evt);
            }
        });

        ex5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ex5ActionPerformed(evt);
            }
        });

        ex6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ex6ActionPerformed(evt);
            }
        });

        ex7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ex7ActionPerformed(evt);
            }
        });

        ex8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ex8ActionPerformed(evt);
            }
        });

        jLabel4.setText("Non-Weighted?");

        weight1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weight1ActionPerformed(evt);
            }
        });

        weight2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weight2ActionPerformed(evt);
            }
        });

        weight3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weight3ActionPerformed(evt);
            }
        });

        weight4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weight4ActionPerformed(evt);
            }
        });

        weight5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weight5ActionPerformed(evt);
            }
        });

        weight6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weight6ActionPerformed(evt);
            }
        });

        weight7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weight7ActionPerformed(evt);
            }
        });

        weight8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weight8ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("**Exempt classes or exams to be left blank");

        calcGPA.setText("Calculate GPA");
        calcGPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcGPAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sem1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sem3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sem4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sem5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sem6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sem7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sem8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(sem2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ex1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ex2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ex3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ex4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ex5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ex6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ex7, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ex8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(weight6)
                                    .addComponent(weight5)
                                    .addComponent(weight4)
                                    .addComponent(weight1)
                                    .addComponent(jLabel4)
                                    .addComponent(weight8)
                                    .addComponent(weight7)
                                    .addComponent(weight3)
                                    .addComponent(weight2)))
                            .addComponent(jLabel5)
                            .addComponent(calcGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gpa, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ex1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(weight1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ex2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(weight2))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ex3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(weight3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sem4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ex4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(weight4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sem5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ex5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(weight5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sem6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ex6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(weight6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sem7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ex7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(weight7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sem8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ex8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(weight8))
                .addGap(18, 18, 18)
                .addComponent(calcGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gpa)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem1ActionPerformed

    }//GEN-LAST:event_sem1ActionPerformed

    private void sem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem2ActionPerformed

    }//GEN-LAST:event_sem2ActionPerformed

    private void sem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem3ActionPerformed

    }//GEN-LAST:event_sem3ActionPerformed

    private void sem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem4ActionPerformed

    }//GEN-LAST:event_sem4ActionPerformed

    private void sem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem5ActionPerformed

    }//GEN-LAST:event_sem5ActionPerformed

    private void sem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem6ActionPerformed

    }//GEN-LAST:event_sem6ActionPerformed

    private void sem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem7ActionPerformed

    }//GEN-LAST:event_sem7ActionPerformed

    private void sem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sem8ActionPerformed

    }//GEN-LAST:event_sem8ActionPerformed

    private void ex1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ex1ActionPerformed

    }//GEN-LAST:event_ex1ActionPerformed

    private void ex2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ex2ActionPerformed

    }//GEN-LAST:event_ex2ActionPerformed

    private void ex3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ex3ActionPerformed

    }//GEN-LAST:event_ex3ActionPerformed

    private void ex4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ex4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ex4ActionPerformed

    private void ex5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ex5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ex5ActionPerformed

    private void ex6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ex6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ex6ActionPerformed

    private void ex7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ex7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ex7ActionPerformed

    private void ex8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ex8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ex8ActionPerformed

    private void weight1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weight1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weight1ActionPerformed

    private void weight2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weight2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weight2ActionPerformed

    private void weight3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weight3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weight3ActionPerformed

    private void weight4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weight4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weight4ActionPerformed

    private void weight5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weight5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weight5ActionPerformed

    private void weight6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weight6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weight6ActionPerformed

    private void weight7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weight7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weight7ActionPerformed

    private void weight8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weight8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weight8ActionPerformed

    private void calcGPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcGPAActionPerformed
        gpa.setText("");
        numClasses = 0;
        Arrays.fill(classes, -1);
        Arrays.fill(exams, -1);
        nonscale.clear();
        scale.clear();
        we.clear();
        if (sem1.getText().length() > 0){
            numClasses++;
            classes[0] = Integer.parseInt(sem1.getText());
            we.add(weight1.isSelected());
        }
        if (sem2.getText().length() > 0){
            numClasses++;
            classes[1] = Integer.parseInt(sem2.getText());
            we.add(weight2.isSelected());
        }
        if (sem3.getText().length() > 0){
            numClasses++;
            classes[2] = Integer.parseInt(sem3.getText());
            we.add(weight3.isSelected());
        }
        if (sem4.getText().length() > 0){
            numClasses++;
            classes[3] = Integer.parseInt(sem4.getText());
            we.add(weight4.isSelected());
        }
        if (sem5.getText().length() > 0){
            numClasses++;
            classes[4] = Integer.parseInt(sem5.getText());
            we.add(weight5.isSelected());
        }
        if (sem6.getText().length() > 0){
            numClasses++;
            classes[5] = Integer.parseInt(sem6.getText());
            we.add(weight6.isSelected());
        }
        if (sem7.getText().length() > 0){
            numClasses++;
            classes[6] = Integer.parseInt(sem7.getText());
            we.add(weight7.isSelected());
        }
        if (sem8.getText().length() > 0){
            numClasses++;
            classes[7] = Integer.parseInt(sem8.getText());
            we.add(weight8.isSelected());
        }
        if (ex1.getText().length() > 0)
            exams[0] = Integer.parseInt(ex1.getText());
        if (ex2.getText().length() > 0)
            exams[1] = Integer.parseInt(ex2.getText());
        if (ex3.getText().length() > 0)
            exams[2] = Integer.parseInt(ex3.getText());
        if (ex4.getText().length() > 0)
            exams[3] = Integer.parseInt(ex4.getText());
        if (ex5.getText().length() > 0)
            exams[4] = Integer.parseInt(ex5.getText());
        if (ex6.getText().length() > 0)
            exams[5] = Integer.parseInt(ex6.getText());
        if (ex7.getText().length() > 0)
            exams[6] = Integer.parseInt(ex7.getText());
        if (ex8.getText().length() > 0)
            exams[7] = Integer.parseInt(ex8.getText());
        for (int i = 0; i < 8; i++) 
        {
            if (classes[i] > -1 && exams[i] > -1)
                nonscale.add(Math.round((float)(classes[i]*6.0 + exams[i]) / 7));
            if (classes[i] > -1 && exams[i] == -1)
                nonscale.add(classes[i]);
        }
        for(int no : nonscale)
        {
            String convert = "";
            String first = no / 10 + "";
            switch (first){
                case "10":
                    convert += 6 + "";
                    break;
                case "9" : 
                    convert += 5 + "";
                    break;
                case "8":
                    convert += 4 + "";
                    break;
                case "7":
                    convert += 3 + "";
                    break;
                case "6":
                    convert += 2 + "";
                    break;
                case "5":
                    convert += 1 + "";
                    break;
                default: 
                    convert += 0 + "";
                    break;
            }
            if (convert.equals("6"))
                convert += ".0";
            else
                convert += "." + no % 10 + "";
            scale.add(Double.parseDouble(convert));
        }
        for (int i = 0; i < scale.size(); i++)
        {
            if (we.get(i))
                scale.set(i, (scale.get(i) - 1.0));
        }
        double sum = 0;
        for (Double data : scale)
        {
            sum += data;
        }
        sum /= numClasses;
        //DecimalFormat trunc = new DecimalFormat("#.00000");
       // String formatted = trunc.format(sum);
        gpa.setText(String.format("%.5f", sum));
    }//GEN-LAST:event_calcGPAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GPAcalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GPAcalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GPAcalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GPAcalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GPAcalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton calcGPA;
    private javax.swing.JTextField ex1;
    private javax.swing.JTextField ex2;
    private javax.swing.JTextField ex3;
    private javax.swing.JTextField ex4;
    private javax.swing.JTextField ex5;
    private javax.swing.JTextField ex6;
    private javax.swing.JTextField ex7;
    private javax.swing.JTextField ex8;
    private javax.swing.JTextField gpa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField sem1;
    private javax.swing.JTextField sem2;
    private javax.swing.JTextField sem3;
    private javax.swing.JTextField sem4;
    private javax.swing.JTextField sem5;
    private javax.swing.JTextField sem6;
    private javax.swing.JTextField sem7;
    private javax.swing.JTextField sem8;
    private javax.swing.JRadioButton weight1;
    private javax.swing.JRadioButton weight2;
    private javax.swing.JRadioButton weight3;
    private javax.swing.JRadioButton weight4;
    private javax.swing.JRadioButton weight5;
    private javax.swing.JRadioButton weight6;
    private javax.swing.JRadioButton weight7;
    private javax.swing.JRadioButton weight8;
    // End of variables declaration//GEN-END:variables
}
